import type { Metadata } from "next";

import "./globals.css";
import  SmoothScroll  from '@/utils/SmoothScroll';
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html
      lang="en"
      className={cn("font-tight", "h-full", "antialiased", "font-sans", inter.variable)}
    >
      <body className="bg-dark-bg flex font-tight h-full overflow-x-hidden">
        <SmoothScroll >
          {children}
        </SmoothScroll>
        </body>

    </html>
  );
}
